id: P001818
initial_creation_type: ocr
created_at: 30/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG16734
  title: ཐེ་ཨེནཏྲནཅེ་གཏེ་ཕོ༹ར་ཐེ་ཝིསེ ༼སེཅཏིཨོན་ཨཱིཨཱིཨཱི༽
  author: ''
  volumes:
    5c1f7db937c34409a4294e7929269e6c:
      image_group_id: I1KG16775
      title: ''
      volume_number: 1
      total_pages: 322
      base_file: v001.txt
    804a700deb8c44008fe8acd68218121e:
      image_group_id: I1KG16776
      title: ''
      volume_number: 2
      total_pages: 336
      base_file: v002.txt
