id: I97694D50
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-30T12:27:50+00:00'
last_modified: '2022-06-07T15:15:37.678552+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16734
  title: ཐེ་ཨེནཏྲནཅེ་གཏེ་ཕོ༹ར་ཐེ་ཝིསེ ༼སེཅཏིཨོན་ཨཱིཨཱིཨཱི༽
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '4906':
      image_group_id: I1KG16775
      title: ''
      total_pages: 322
      order: 1
      base_file: 4906.txt
    81EB:
      image_group_id: I1KG16776
      title: ''
      total_pages: 336
      order: 2
      base_file: 81EB.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
