id: I97694D50
legacy_id: P001818
ocr_import_info:
  bdrc_scan_id: W1KG16734
  source: bdrc
  ocr_info:
    timestamp: '2020-03-30T12:25:25'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-27T06:15:49.137746+00:00'
last_modified: 2022-08-27 14:17:18.507462
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG16734
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG16734
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: the entrance gate for the wise (section III)
  author: ངག་དབང་སྐལ་ལྡན།
statistics:
  ocr_word_mean_confidence_index: 0.9207649877549298
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1KG16775:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16775
      total_pages: 322
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG16775.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9200174559996585
    legacy_id: v001
  I1KG16776:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG16776
      total_pages: 336
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG16776.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9213733425596489
    legacy_id: v002
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
